/**
 * This module processes the JSON file generated by
 * the export.jxa into temporary folder. The location
 * of the file is given as argument. Example:
 *
 * node scripts/process.js ./tmp/output.json
 */
const path = require('path')
const jsonfile = require('jsonfile')
const { parse, format } = require('date-fns')
const groupby = require('lodash.groupby')
const { red, blue, yellow, green, bold, gray } = require('colorette')

function parseDuration(rawValue) {
  const decimalValue = parseFloat(rawValue / 3600)
  const hours = parseInt(decimalValue)
  const minutes = ((decimalValue % 1) * 60).toFixed(0)

  return {
    hours,
    minutes
  }
}

function formatDecimalHours(rawValue) {
  const hours = parseFloat(rawValue/3600).toFixed(2)
  return `${hours} hrs`
}

function formatHours(rawValue) {
  const parsed = parseDuration(rawValue)
  return `${parsed.hours}:${parsed.minutes < 10 ? `0${parsed.minutes}`: parsed.minutes }`
}

function formatRoundHours(rawValue) {
  const parsed = parseDuration(rawValue)
  if (parsed.minutes < 15) {
    parsed.minutes = 0
  }
  else if (parsed.minutes >= 15 && parsed.minutes < 30) {
    parsed.minutes = 30
  }
  else if (parsed.minutes >= 30 && parsed.minutes < 45) {
    parsed.minutes = 30
  }
  else if (parsed.minutes >= 45) {
    parsed.hours += 1
    parsed.minutes = 0
  }
  return `${parsed.hours},${parsed.minutes * 100 / 60}`
}

function filterEntry(entry) {
  if (entry.project.toLocaleLowerCase().indexOf('personal') !== -1) {
    return false
  }
  return true
}

function filterProject(projectName) {
  if (projectName.toLocaleLowerCase().indexOf('personal') !== -1) {
    return false
  }
  return true
}

async function processFile(inputPath) {
  let output = []

  try {
    const data = await jsonfile.readFile(inputPath)
    const grouper = entry => {
      return format(entry.startDate, 'YYYY-MM-DD')
    }
    const groupedByDate = groupby(data, grouper)

    // Iterate all days
    const dayOutput = Object.keys(groupedByDate).map(dayKey => {
      const groupedByProject = groupby(groupedByDate[dayKey], 'project')
      let dayOutput = []
      let weekDay = format(parse(dayKey), 'ddd')
      let daySum = 0

      // Iterate time entries per day/project
      const projectOutput = Object.keys(groupedByProject).filter(filterProject).map(projectKey => {
        let dayProjectSum = 0
        let notes = []
        let dayProjects = []

        // Iterate all time entries withing project
        const groupedByActivity = groupby(groupedByProject[projectKey].filter(filterEntry), 'taskActivityTitle')
        // Iterate all tasks within day
        Object.keys(groupedByActivity).forEach(activityKey => {
          const durationSum = groupedByActivity[activityKey].reduce((prevValue, timeEntry) => prevValue + timeEntry.duration || 0, 0)
          dayProjectSum += durationSum
          dayProjects.push({
            activityKey,
            duration: durationSum,
          })
        })

        const decimalHours = formatDecimalHours(dayProjectSum)
        const hours = formatHours(dayProjectSum)
        const roundHours = formatRoundHours(dayProjectSum)
        const notePrint = ''

        const outputLines = []
        outputLines.push(`  - ${yellow(projectKey)}: ${green(decimalHours)} ${gray('/')} ${blue(hours)} ${gray('/')} ${red(roundHours + ' hrs')} ${notePrint}`)
        dayProjects.forEach(dayProjectEntry => {
          const decimalHours = formatDecimalHours(dayProjectEntry.duration)
          const hours = formatHours(dayProjectEntry.duration)
          const roundHours = formatRoundHours(dayProjectEntry.duration)
          outputLines.push(`    ${gray('>>')} ${dayProjectEntry.activityKey}: : ${green(decimalHours)} ${gray('/')} ${blue(hours)} ${gray('/')} ${red(roundHours + ' hrs')}`)
        })

        return outputLines.join('\n')
      })

      const decimalHours = formatDecimalHours(daySum)
      const hours = formatHours(daySum)
      const roundHours = formatRoundHours(daySum)
      // Add day separator
      dayOutput.push(`[ ${bold(red(weekDay.toLocaleUpperCase()))} ${dayKey} (${green(decimalHours)} / ${blue(hours)} / ${red(roundHours)}) ]`)
      dayOutput = dayOutput.concat(projectOutput.sort())
      dayOutput.push('')

      return dayOutput.join('\n')
    })

    output = output.concat(dayOutput)
  }
  catch (error) {
    console.error(error);
  }

  console.log(output.join('\n'));
}

function main() {
  const args = process.argv
  if (args.length !== 3) {
    return process.exit(-1)
  }

  const inputPath = args[args.length - 1]
  processFile(path.join(__dirname, '..',  inputPath))
}


main()
